### ISSUE TITLE
Timed out waiting for device /dev/disk/by-label/BOOT.

### ISSUE THREAD

**Issue by cnSchwarzer** [eugene-tarassov/vivado-risc-v#131]
I'm running on board `nexys-video` `rocket64b2` and everything default. Is it normal?
QEMU works fine.

```
make CONFIG=rocket64b2 BOARD=nexys-video bitstream
./mk-sd-card 
make CONFIG=rocket64b2 BOARD=nexys-video flash
``` 

![image](https://user-images.githubusercontent.com/29846655/216761538-5c0f3961-b58b-4f6d-8277-b554c3491204.png)
![image](https://user-images.githubusercontent.com/29846655/216761551-97403a33-8d3d-429c-958b-425282440f6c.png)

**Comment by cnSchwarzer** [comment]
I checked the QEMU and the boot contains boot.elf, etc... So is it mounting itself?

**Comment by cnSchwarzer** [comment]
Might related to https://github.com/eugene-tarassov/vivado-risc-v/issues/119#issuecomment-1336507535

**Comment by eugene-tarassov** [comment]
Yes, it is related to that comment, udev daemon hits timeout on a slow CPU.
The problem is a regression in the mainstream Linux, I have not seen a solution yet.

Workaround is to increase timeouts in the Linux config, see [this comment](https://github.com/eugene-tarassov/vivado-risc-v/issues/119#issuecomment-1337976249) for the script.
