### ISSUE TITLE
Ethernet support seems broken for Nexys Video

### ISSUE THREAD

**Issue by Leo-Z-Li** [eugene-tarassov/vivado-risc-v#158]
Hi dev, 

I found that ethernet support seems broken for nexys video, in the debian system there is no correct interface if I run /sbin/ifconfig, there is only lo:

> _debian@debian:~$ /sbin/ifconfig
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 24  bytes 1944 (1.8 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 24  bytes 1944 (1.8 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0_

Also while the system boots, there are errors:

> _U-Boot 2022.01-dirty (May 02 2023 - 18:57:29 +0800)
CPU:   rv64imafdc
> Model: freechips,rocketchip-vivado
> DRAM:  512 MiB
> MMC:   mmc0@60000000: 0
> Loading Environment from nowhere... OK
> In:    uart@60010000
> Out:   uart@60010000
> Err:   uart@60010000
> Net:   No ethernet found.
> Hit any key to stop autoboot:  0_ 

> _[  OK  ] Finished Remove Stale Onli…ext4 Metadata Check Snapshots.
> [FAILED] Failed to start Helper to …chronize boot up for ifupdown.
> See 'systemctl status ifupdown-pre.service' for details.
> [DEPEND] Dependency failed for Raise network interfaces.
> [  OK  ] Reached target Network.
> [  OK  ] Reached target Network is Online._

I tried both makefile and pre-build bitstream and they all don't work. Could someone check this plz :)

**Comment by eugene-tarassov** [comment]
In U-Boot, Ethernet is not supported yet. In Linux, Ethernet works OK. I checked test automation logs, the last Nexys Video test was successful  just 4 hour ago.

`Failed to start Helper to …chronize boot up for ifupdown` is indication of a problem in Linux systemd scripts, probably a timeout when it tries to obtain a DHCP lease from local network. I recommend to check Linux system logs for error messages.

**Comment by LeooLevinn** [comment]
I've tried release v3.3.0 and that works fine, it obtained a DHCP address automatically and there are no failed/depend logs while the system boots. 

Also tried static IP on v3.4.0 but doesn't work either. Seems the system can't detect the ethernet interface.

System boot logs for 3.3.0 :

> [  286.818297] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
> [  OK  ] Started System Logging Service.
> [  OK  ] Finished Remove Stale Onli…ext4 Metadata Check Snapshots.
> [  OK  ] Finished Raise network interfaces.
> [  OK  ] Reached target Network.
> [  OK  ] Reached target Network is Online.

**Comment by mbelda** [comment]
I have the same issue with the VC707.

~~~
[  OK  ] Started Regular background program processing daemon.
         Starting Remove Stale Onli…t4 Metadata Check Snapshots...
[  OK  ] Finished Remove Stale Onli…ext4 Metadata Check Snapshots.
[FAILED] Failed to start Helper to …chronize boot up for ifupdown.
See 'systemctl status ifupdown-pre.service' for details.
[DEPEND] Dependency failed for Raise network interfaces.
[  OK  ] Reached target Network.
[  OK  ] Reached target Network is Online.
~~~

The problem seems to be on the bitstream, since using the one provided on release everything works. But when using one of mine Rocketb2gem8 (it is provided at rocket.scala) the ethernet fails.

Do I have to include some special module on the bitstream? 
Can you tell me which architecture has the bitstream on the release page?

**Comment by eugene-tarassov** [comment]
No, you don't need to include some special module. It is a Linux problem. The problem is some bitstreams have lower clock frequency than others. In particular, Rocketb2gem8 has low clock frequency because of complexity of Gemmini. So Linux needs more time to start services and hits timeout in the system daemon configuration. I have create new release 3.5.0, it has rootfs and SD card images with increased timeout settings, it should boot OK on Rocketb2gem8. Run `./mk-sd-card` to write new image to SD card.

**Comment by mbelda** [comment]
Ok but I would prefer to increase the frecuency since I am using a Dummy Gemmini configuration to obtain performance results.

Can you tell me where is the frecuency fixed?

**Comment by mbelda** [comment]
I updated to the 3.5.0 tag and I get the same log with the same problem, so the problem is not fixed (at least for vc707).

**Comment by Leo-Z-Li** [comment]
I think this is because the core is running so slow to initialize the ethernet and the system recognizes it as a failure. Also it would stuck at starting ifupdown services for a long time because it is slow. for me i do not need ethernet services so i simply do _sudo apt remove ifupdown_. I run rocketb1gem4 on nexys video, after removing the ifupdown the system boot time reduced from 1+hrs to about 20mins.
