### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Ammadali90** [eugene-tarassov/vivado-risc-v#29]
Hi,

I got the following error messages when I run make update-submodules.

fatal: clone of 'git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git' into submodule path '/home/ams/Documents/Pytorch-dir/ACU-4/Docker/vivado-risc-v/linux-stable' failed
Failed to clone 'linux-stable' a second time, aborting
make: *** [Makefile:11: update-submodules] Error 1

Do you know the reason for that error?

Thanks and best regards,
Ammad

**Comment by eugene-tarassov** [comment]
This is usually caused by slow or unreliable connection to git.kernel.org, which the main server storing Linux source code.
Just try again until the download succeeds.

Depending on your location, one of public mirrors of git.kernel.org might work better, for example one at https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable
