### ISSUE TITLE
Increase FIFO size in UART

### ISSUE THREAD

**Issue by tirumalnaidu** [eugene-tarassov/vivado-risc-v#38]
Can we increase the FIFO size by configuring "fifo_ptr_bits" parameter in uart.v without any complications in working on the UART controller?

**Comment by eugene-tarassov** [comment]
Increasing the FIFO size can cause complications for XON/XOFF protocol, because it can take more time to react to XOFF character coming from the other side. The UART implements FIFO bypass for XON/XOFF in the TX, but not in the RX. If you don't use XON/XOFF,  increasing "fifo_ptr_bits" should be fine.
